name: Build and Deploy

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install Hugo
        run: |
          HUGO_DOWNLOAD=hugo_extended_${HUGO_VERSION}_Linux-64bit.tar.gz
          wget https://github.com/gohugoio/hugo/releases/download/v${HUGO_VERSION}/${HUGO_DOWNLOAD}
          tar xvzf ${HUGO_DOWNLOAD} hugo
          mv -v hugo ${HOME}/hugo
        env:
          HUGO_VERSION: 0.83.1

      - name: Hugo Version
        run: ${HOME}/hugo version

      - name: Hugo Build
        run: |
          ${HOME}/hugo -v
          sed -i 's/Opala 75 - Opala 75/Opala/g' public/index.html        

      - name: S3 sync
        run: |
          aws s3 ls s3://${{ secrets.S3_BUCKET }}/ --summarize
          aws s3 rm s3://${{ secrets.S3_BUCKET }} --recursive
          aws s3 sync public/ s3://${{ secrets.S3_BUCKET }}/
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}

      - name: Invalidate CloudFront cache
        run: aws cloudfront create-invalidation --distribution-id=${{ secrets.CLOUDFRONT_ID }} --paths /
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}

      - name: CloudFront status
        run: |
          sleep 5
          aws cloudfront list-distributions --query "DistributionList.Items[].{Status: Status, Domain: DomainName, OriginDomainName: Origins.Items[0].DomainName}[?contains(OriginDomainName, '${{ secrets.S3_BUCKET }}')] | [0]" | grep -q Deployed
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}